<a href="https://colab.research.google.com/github/nabinstha1234/Disease-Prediction-from-Symptoms/blob/master/numpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NUmpy Arrays:
    1. Allows several Mathematical Operations
    2. Faster operations

In [2]:
import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list 

In [10]:
python_list = [i for i in range(10000)]

start_time= process_time()

python_list=[i+5 for i in python_list]

end_time= process_time()

print(end_time-start_time) #this will print amount of time in second required to complete this execution

0.0006788189999999972


In [11]:
np_array = np.array([ i for i in range(10000)])
start_time1= process_time()

np_array+=5

end_time1= process_time()
print(end_time1-start_time1)


0.0002002509999998736


Numpy Arrays 

In [12]:
#list 
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [14]:
# creating arrays in numpy
np_arary = np.array([1,2,3,4,5])
print(np_arary)
type(np_arary)

[1 2 3 4 5]


numpy.ndarray

In [15]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
a.shape

(4,)

In [19]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
b.shape

(2, 4)

In [21]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initials Placeholders in numpy arrays

In [22]:
# create a numpy arrays of Zeros
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# create a numpy arrays of ones
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# array of particular value
y = np.full((4,5),5)
y

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
# create an identity matrix
# identity matrix has same number of rows and columns
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# create an numpy array with random values
b = np.random.random((3,4))
b

array([[0.12515637, 0.22388555, 0.47132255, 0.25226375],
       [0.80183413, 0.21832516, 0.5810726 , 0.97824149],
       [0.70489151, 0.31036904, 0.84019146, 0.75580097]])

In [30]:
# rndom integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[68 48 39 80 81]
 [42 76 11 57 77]
 [84 48 58 29 56]]


In [31]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
d

array([10., 15., 20., 25., 30.])

In [32]:
# array of evenly spaced values --> specifing the step
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [34]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array =np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Ananysing a numpy array

In [35]:
c = np.random.randint(10,90,(5,5))
c

array([[11, 17, 89, 16, 14],
       [36, 73, 81, 43, 39],
       [10, 17, 30, 46, 62],
       [47, 50, 14, 49, 55],
       [15, 59, 51, 57, 66]])

In [36]:
# array dimesnion
print(c.shape)

(5, 5)


In [38]:
# number of dimesnions
print(c.ndim)

2


In [39]:
# number of elements in an array 
print(c.size)

25


In [40]:
# checking the datatype of the value in  the array
print(c.dtype)

int64


Mathematical operations on a np array

In [41]:
list1 = [1,2,3,4,5]

In [42]:
list2= [6,7,8,9,10]

In [43]:
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
b

[[6 2 6]
 [5 1 1]
 [4 7 5]]


array([[10, 15, 13],
       [12, 10, 15],
       [17, 17, 15]])

In [45]:
a+b

array([[16, 17, 19],
       [17, 11, 16],
       [21, 24, 20]])

In [46]:
a-b

array([[ -4, -13,  -7],
       [ -7,  -9, -14],
       [-13, -10, -10]])

In [47]:
a*b

array([[ 60,  30,  78],
       [ 60,  10,  15],
       [ 68, 119,  75]])

In [48]:
a/b

array([[0.6       , 0.13333333, 0.46153846],
       [0.41666667, 0.1       , 0.06666667],
       [0.23529412, 0.41176471, 0.33333333]])

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [50]:
print(a)
print(b)

[[6 2 6]
 [5 1 1]
 [4 7 5]]
[[10 15 13]
 [12 10 15]
 [17 17 15]]


In [51]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 17 19]
 [17 11 16]
 [21 24 20]]
[[ -4 -13  -7]
 [ -7  -9 -14]
 [-13 -10 -10]]
[[ 60  30  78]
 [ 60  10  15]
 [ 68 119  75]]
[[0.6        0.13333333 0.46153846]
 [0.41666667 0.1        0.06666667]
 [0.23529412 0.41176471 0.33333333]]


In [53]:
array = np.random.randint(0,10,(2,3))
print(array)

[[3 9 4]
 [9 2 9]]


In [54]:
array.shape

(2, 3)

In [55]:
array.size

6

In [56]:
# transpose
trans = np.transpose(array)
print(trans)
trans.shape

[[3 9]
 [9 2]
 [4 9]]


(3, 2)

In [57]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 9]
 [9 2]
 [4 9]]
(3, 2)


In [58]:
# reshaping array 
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[5 7 8]
 [7 4 3]]
(2, 3)


In [59]:
b = a.reshape(3,2)
print(b)

[[5 7]
 [8 7]
 [4 3]]
